[package]
name = "chave/gunz-duel"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact = "roblox/roact@1.4.4"
signal = "sleitnick/signal@2.0.1"
comm = "sleitnick/comm@0.3.2"
roact-template = "corecii/roact-template@0.2.1"
topbarplus = "aspecky/topbarplus@2.9.1"
profileservice = "4x8matrix/profile-service-fork@1.0.0"
promise = "evaera/promise@4.0.0"
knit = "sleitnick/knit@1.5.3"